apiVersion: v1
kind: Pod
metadata:
  name: my-tensor-pod
  labels:
    app: my-tensor
spec:
  containers:
    - name: tensorflow
      image: tensorflow/tensorflow:latest
      env:
      - name: PASSWORD
        value: "passw0rd"
